spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names:

logging:
  path: logs/exchange/
  config: classpath:logback_default.xml

#Actuator
management.context-path: /actuators

redis:
  exchange:
    port: 6379
    host: localhost

---
spring:
  profiles: local
